### ISSUE TITLE
Add max_digits and decimal_places on DecimalField

### ISSUE THREAD

**Issue by rg3915** [Abdenasser/dr_scaffold#17]
#### Issue Summary

In DecimalField `max_digits=5, decimal_places=2,` is essential.

---

_If this is a bug instead of a question or feature request, please fill out the sections below._

---

#### Steps to Reproduce

This parameters is mandatory to make migrations.

#### What were you expecting to happen?

Add `max_digits=5, decimal_places=2,` on DecimalField.

#### Message error

In my example:

```
SystemCheckError: System check identified some issues:

ERRORS:
ecommerce.OrderItems.price: (fields.E130) DecimalFields must define a 'decimal_places' attribute.
ecommerce.OrderItems.price: (fields.E132) DecimalFields must define a 'max_digits' attribute.
```

**Comment by Abdenasser** [comment]
@rg3915 thank you for reporting, this is a good start if you wanna contribute: you can make the changes to`dr_scaffold/scaffold_templates/model_templates.py` **DECIMALFIELD =**, no tests will be needed ... then open a PR, will be more than happy to see more developers contributing to this.. else, you can expect a fix asap.

**Comment by Abdenasser** [comment]
@rg3915 `pip install dr-scaffold==1.4.3`
