### ISSUE TITLE
Fix second argument on the command line to remove special character

### ISSUE THREAD

**Issue by rg3915** [Abdenasser/dr_scaffold#25]
If type `python manage.py dr_scaffold blog Article: title:char body:text`

type : before or after model name

This generate

```python
class Article:(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    body = models.TextField(null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Article:s"
```

Article with two points.

**Suggestion**

Address this in the argument on command line.

**Comment by Abdenasser** [comment]
@rg3915 sorry, I'm a bit new to Python/Django world but why would you need to add a colon in the model name, is there any use case for that?

**Comment by rg3915** [comment]
@Abdenasser No. I meant that if the person types accidentally, this character should be removed.
I typed it accidentally and generated a lot of errors.
