### ISSUE TITLE
Field description

### ISSUE THREAD

**Issue by matej2** [Abdenasser/dr_scaffold#52]
**Is your feature request related to a problem? Please describe.**
I will use this libary to automatically create models. I want to write description (why a certain field is used for). The best way to do this is to write it in python comment.

**Describe the solution you'd like**
Add an option to write it in brackets when defining fields:

> python manage.py dr_scaffold blog Post body:textfield(Content of the post) author:foreignkey:Author

Would generate:

```
class Post(models.Model):
    body= models.CharField(max_length=255) #Content of the post
    ...
```

It would also add this comment to the admin page (so that it is visible when adding new Post)

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by Abdenasser** [comment]
not relevant, you can do this manually instead!

**Comment by matej2** [comment]
Why, isnt this code generator? I have a metadata libary that includes data types and descriptions, and I would like to use this code generator to add more information for each generated attribute.
