### ISSUE TITLE
Some types of fields are required.

### ISSUE THREAD

**Issue by matej2** [Abdenasser/dr_scaffold#53]
**Is your feature request related to a problem? Please describe.**
When I generate model, I noticed that some types (Number and URL for ex.) are not optional.

**Describe the solution you'd like**
It would be optional, same as CharField. Or is there a reason for this to be non-optional?

**Describe alternatives you've considered**
None.

**Additional context**
N/A

**Comment by Abdenasser** [comment]
for now we are more interested in fixing real issues

**Comment by matej2** [comment]
How is this not a real issue? Why are some attributes optional and some not?
